version: '3'

networks: 
  python_network:
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #    - subnet: 192.168.2.0/24
    #    - gateway: 192.168.2.1

services:
  db:
    # コンテナ名
    container_name: "db"
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: "./mysql.Dockerfile"
    # ホスト側のポート:コンテナ側のポートを指定
    expose:
      - "3306"
    ports:
      - "3306:3306"
      # - target: 3306
      # - published: 3306
      # - protocol: tcp
      # - mode: host
    # 環境変数の指定
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=streamlit_database"
      - "MYSQL_USER=wander"
      - "MYSQL_PASSWORD=password"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - "../db:/var/lib/mysql"
    networks:
     - python_network
        # ipv4_address: 192.168.2.2    

  asdf:
    # image: streamlit:wander
    hostname: wander-server
    container_name: asdf
    build:
      dockerfile: "Dockerfile"
    volumes: 
      - ../:/root/ws
    expose:
      - "8501"
    ports:
      - "8888:8501"
    links:
      - db
    depends_on:
      - db
    working_dir: "/root/ws"
    tty: true
    restart: always
    networks:
      - python_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db #mysqlサービス名を指定
      - PMA_USER=wander
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    tty: true
    restart: always
    networks:
      - python_network